version: '3.4'

services:
  online-ordering-api:
    image: sol-flowers-api
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5000:5000
